name: walturntodo
description: Walturn ToDo
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  abstract_bloc: ^1.0.8
  cloud_firestore: ^4.8.0
  connectivity_plus: ^4.0.1
  firebase_core: ^2.13.1
  flutter_slidable: ^3.0.0
  gap: ^3.0.0
  get_it: ^7.6.0
  intl: ^0.18.0
  storage_repository: ^1.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/